#!/usr/bin/env python
# coding: utf-8

# # Write a Python function to find the Max of three numbers.

# In[1]:


def greatest(x,y,z):
    if x>y and x>z:
        print("The greatest of the three is : ",x)
    elif y>x and y>z:
        print("The greatest of the three is : ",y)
    else:
        print("The greatest of the three is : ",z)
        
a=input(print("Enter the 1st number : ",end=" "))
b=input(print("Enter the 2nd number : ",end=" "))
c=input(print("Enter the 3rd number : ",end=" "))
greatest(a,b,c)


# # Write a Python function that checks whether a passed string is palindrome or not

# In[5]:


def pal(x):
    x=x.casefold()
    y=reversed(x)
    if x==y:
        print("The string is Pallindrome")
        print()
    else:
        print("The string is not pallindrome")
        print()
print("Program for Pallindrome")
s = input(print("Enter the String : ",end=" "))
pal(s)


# # Write a Python function that accepts a string and calculate the number of uppercase letters and lowercase letters
# 

# In[2]:


def calc(s):
    q = len(s)
    cc = 0
    cl = 0
    ss = 0
    for i in range(0,q):
        if s[i].isupper():
            cc=cc+1
        elif s[i].islower():
            cl=cl+1
    print("Number of upper case letter's are : ",cc)
    print("Number of lower case letter's are : ",cl)
    
z = input(print("Enter the String : "))
calc(z)


# # Write a Python function to sum all the numbers in a list

# In[12]:


def add(q):
    x = 0
    x = sum(q)
    print("Sum of the elemnets in list is : ",x)
    
lst = []
n = int(input(print("Enter the no. of elements : ")))
print("Enter the Integer's :")
for i in range (0,n):
    ele = int(input())
    lst.append(ele) 
print(lst)
add(lst)


# # Write a Python function to multiply all the numbers in a list

# In[5]:


def multiplyList(myList) :
    result = 1
    for x in myList:
         result = result * x 
    return result 
     
list1 = []
n = int(input(print("Enter the no. of elements : ")))
print("Enter the Integer's :")
for i in range (0,n):
    ele = int(input())
    list1.append(ele) 
print(multiplyList(list1))


# # Write a Python function that takes a list and returns a new list with unique elements of the first list

# In[7]:


list1 = []
n = int(input(print("Enter the no. of elements : ")))
print("Enter the Integer's :")
for i in range (0,n):
    ele = int(input())
    list1.append(ele) 
    
list2 = set(list1)
list2 = list(list2)
print("Origional List : ",list1)
print("Unique List : ",list2)


# In[ ]:




