#!/usr/bin/env python
# coding: utf-8

# # Write a Python program to remove duplicates from a list

# In[8]:


lst = [] 
n = int(input("Enter number of elements : ")) 
for i in range(0,n): 
    ele = input()
    lst.append(ele)    
print(lst) 
seq=set(lst)
lst=list(seq)
lst.sort()
print(lst)


# # Write a Python program to compute the similarity between two lists.
# # Write a Python program to get the difference between the two lists

# In[6]:


from collections import Counter
color1 = []
m = int(input("Enter number of elements : ")) 
print("Enter the Elements : ")
print()
for i in range(0,m): 
    ele = input()
    color1.append(ele)  
color2 = []
n = int(input("Enter number of elements : ")) 
print("Enter the Elements : ")
print()
for i in range(0,n): 
    ele = input()
    color2.append(ele)  

diff1 = list(set(color1) - set(color2))
diff2 = list(set(color2) - set(color1))
print("Difference is : ")
diff = diff1+diff2
print(diff)

counter1 = Counter(color1)
counter2 = Counter(color2)
print("Similarity is : ")
print("Color1-Color2: ",list(counter1 - counter2))
print("Color2-Color1: ",list(counter2 - counter1))


# # Write a Python program to get the frequency of the elements in a list

# In[3]:


list = [] 
n = int(input("Enter number of elements : ")) 
for item in range(0,n): 
    ele = input()
    list.append(ele) 
    
frequency = {}
for item in list:
    if (item in frequency):
        frequency[item] += 1
    else:
        frequency[item] = 1
for key, value in frequency.items():
    print("% s -> % d" % (key, value))


# # Write a Python function that takes a list of words and returns the length of the longest one

# In[6]:


lst = []
n = int(input("Enter number of elements : "))
print("Enter the words")
for i in range(0,n): 
    ele = input()
    lst.append(ele)

y=0
x = len(lst[0])    

for i in range(1,n):
    z=len(lst[i])
    if z>x:
        x=z
        y=i

print("The Longest Word is "+ lst[y] +" and the word size is ",x)


# # Write a Python program to count the occurrences of each word in a given sentence

# In[14]:


str = input(print ("Enter the sentence : ")) 
str = str.split()          
unique_words = set(str)  
  
for words in unique_words : 
    print('Frequency of ', words , 'is :', str.count(words)) 


# # Write a Python program to count and display the vowels of a given text

# In[25]:


str = input(print ("Enter the sentence : "))       
u = set(str)  
for i in u : 
    if i == 'a' or i == 'e' or i == 'i' or i == 'o' or i == 'u':
        print ("Frequency of ", i , " is : ", str.count(i)) 


# # Write a Python script to generate and print a dictionary that contains a number (between 1 and n) in the form (x, x*x)
# 

# In[26]:


n=int(input("Enter a number:"))
d={x:x*x for x in range(1,n+1)}
print(d)


# # Write a Python program to combine two dictionary adding values for common keys ● d1 = {'a': 100, 'b': 200, 'c':300} ● d2 = {'a': 300, 'b': 200, 'd':400} ● Sample output: Counter({'a': 400, 'b': 400, 'd': 400, 'c': 300})

# In[27]:


d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

d3 = dict(d1) 

d3.update(d2) 

for i, j in d1.items():

    for x, y in d2.items():

        if i == x:

            d3[i]=(j+y)

print(d3)


# # Write a Python program to print all unique values in a dictionary ● Sample Data : [{"V":"S001"}, {"V": "S002"}, {"VI": "S001"}, {"VI": "S005"}, {"VII":"S005"},{"V":"S009"},{"VIII":"S007"}] ● Expected Output : Unique Values: {'S005', 'S002', 'S007', 'S001', 'S009'}

# In[28]:


L = [{"V":"S001"}, {"V": "S002"}, {"VI": "S001"}, {"VI": "S005"}, {"VII":"S005"}, {"V":"S009"},{"VIII":"S007"}]
print("Original List: ",L)
u_value = set( val for dic in L for val in dic.values())
print("Unique Values: ",u_value)


# In[ ]:




