#!/usr/bin/env python
# coding: utf-8

# # guess the movie name

# In[3]:


import firebase_admin
from firebase_admin import credentials

cred = credentials.Certificate("prac1-b8138-firebase-adminsdk-bo7fn-34c3c1ee44.json")
firebase_admin.initialize_app(cred)
print("Working")


# In[4]:


from firebase_admin import firestore


# In[6]:


db = firestore.client()
doc_ref = db.collection("movies").document("Bollywood")

data = {"Name":["mirzapur","kgf","asur","family-man","dangal"],
       "collection":[400,500,200,100,600]}
doc_ref.set(data)
print("done")


# In[7]:


db = firestore.client()

docs = db.collection("movies").stream()
for d in docs:
    database = d.to_dict()


# In[9]:


import random
movie = database["Name"]
player = input("Write your Name: ")
print("Guess the character: ")
print("You have 10 chance to get the movie name: ")
print("Best of luck!",player)


count = 10

geuss= ""

word = random.choice(movie) #war

while count>0:
    fail = 0
    for char in word:
        if char in geuss:
            print(char)
        else:
            print("_")
            fail+=1
            
            
    if fail==0:
        print("Congratulation you won!!!")
        print("Movie Name was:",word)
        break
        
    g = input("Enter your character: ")
    geuss = geuss+g
    
    if g not in word:
        count = count-1
        print("Wrong Answer:(")

        print("You have ",count,"more geusses")

